# experience name
save_root: /home/zns/Codes/litelanenet_pytorch
exp_name: llnet_ds-culane_div8

# model
model_type: llnet_ds
pretrain_model:
checkpoint:

# data_loader
dataset_type: CULaneDiv8
data_root: /home/zns/dataset/lane/culane
batch_size: 12
num_workers: 6

# optimizer
loss_type: LaneLoss
lr: 0.01
weight_decay: 0.0001
momentum: 0.9

# train_strategy
epochs: 50
check_interval: 1
warmup_steps: 1000
lr_decay_steps: [25, 40]
